test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.master_key="YUNOHOST-API-KEY-202020201456452135"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.30d48110ea0c820c89ab8ade34e415f07b5b0b86.name = "Upgrade from #13"