#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by Yunohost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing Meilisearch service..."
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
